import { persianNumbers } from "../../utils/persian-text";

import {
  IDataGridColumn,
  IDataGridData,
} from "../../components/DataGrid/DataGrid.types";

export const columns: IDataGridColumn[] = [
  {
    field: "userId",
    title: "شناسه کاربر",
  },
  {
    field: "username",
    title: "نام و نام‌ خانوادگی",
  },
  { field: "email", title: "ایمیل" },
  { field: "phoneNo", title: "شماره تلفن" },
  {
    field: "sessionsCount",
    title: "تعداد جلسات",
  },
  {
    field: "creationDate",
    title: "تاریخ ایجاد",
  },
  {
    field: "lastVisited",
    title: "آخرین بازدید",
  },
];

export const data: IDataGridData[] = [
  {
    id: "0",
    userId: "mohsenA",
    username: "محسن عزیزی",
    email: "mohsen.azizi@gmail.com",
    phoneNo: persianNumbers("09121234567"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "1",
    userId: "hamid",
    username: "حمید عزیزی",
    email: "hamid.a@gmail.com",
    phoneNo: persianNumbers("09121234567"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "2",
    userId: "Ali",
    username: "علی مطهرنیا",
    email: "ali.mot@gmail.com",
    phoneNo: persianNumbers("09351254985"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "3",
    userId: "jafar",
    username: "جعفر سازگار",
    email: "jafar.consistent@gmail.com",
    phoneNo: persianNumbers("09123452579"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "4",
    userId: "Sobhan",
    username: "رضا سبحانی",
    email: "reza.son@gmail.com",
    phoneNo: persianNumbers("09165468254"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "5",
    userId: "Gorji",
    username: "مینا گرجی",
    email: "mina.Gorj@gmail.com",
    phoneNo: persianNumbers("09117459862"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "6",
    userId: "IraniMahmoud",
    username: "محمود ایرانی",
    email: "mah.irani@gmail.com",
    phoneNo: persianNumbers("09332546564"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "7",
    userId: "SaSo",
    username: "صبا سلطانی",
    email: "sab.soltan@gmail.com",
    phoneNo: persianNumbers("091245682135"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "8",
    userId: "Simin",
    username: "سیمین مرادی",
    email: "simin.mo@gmail.com",
    phoneNo: persianNumbers("09375668752"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "9",
    userId: "Sam",
    username: "سمانه صابر",
    email: "sam.sa@gmail.com",
    phoneNo: persianNumbers("09121111111"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "10",
    userId: "hamid",
    username: "حمید عزیزی",
    email: "hamid.a@gmail.com",
    phoneNo: persianNumbers("09121234567"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "11",
    userId: "Ali",
    username: "علی مطهرنیا",
    email: "ali.mot@gmail.com",
    phoneNo: persianNumbers("09351254985"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "12",
    userId: "jafar",
    username: "جعفر سازگار",
    email: "jafar.consistent@gmail.com",
    phoneNo: persianNumbers("09123452579"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "13",
    userId: "Sobhan",
    username: "رضا سبحانی",
    email: "reza.son@gmail.com",
    phoneNo: persianNumbers("09165468254"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "14",
    userId: "Gorji",
    username: "مینا گرجی",
    email: "mina.Gorj@gmail.com",
    phoneNo: persianNumbers("09117459862"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "15",
    userId: "IraniMahmoud",
    username: "محمود ایرانی",
    email: "mah.irani@gmail.com",
    phoneNo: persianNumbers("09332546564"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "16",
    userId: "SaSo",
    username: "صبا سلطانی",
    email: "sab.soltan@gmail.com",
    phoneNo: persianNumbers("091245682135"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "17",
    userId: "Simin",
    username: "سیمین مرادی",
    email: "simin.mo@gmail.com",
    phoneNo: persianNumbers("09375668752"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "18",
    userId: "Sam",
    username: "سمانه صابر",
    email: "sam.sa@gmail.com",
    phoneNo: persianNumbers("09121111111"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "19",
    userId: "Sobhan",
    username: "رضا سبحانی",
    email: "reza.son@gmail.com",
    phoneNo: persianNumbers("09165468254"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "20",
    userId: "Gorji",
    username: "مینا گرجی",
    email: "mina.Gorj@gmail.com",
    phoneNo: persianNumbers("09117459862"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "21",
    userId: "Sobhan",
    username: "رضا سبحانی",
    email: "reza.son@gmail.com",
    phoneNo: persianNumbers("09165468254"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
  {
    id: "22",
    userId: "Gorji",
    username: "مینا گرجی",
    email: "mina.Gorj@gmail.com",
    phoneNo: persianNumbers("09117459862"),
    sessionsCount: persianNumbers("10"),
    creationDate: persianNumbers("1399/08/25"),
    lastVisited: persianNumbers("1399/12/04"),
  },
];
