/* eslint-disable */
export const FiltersInitialValues = [
  ["userId", true],
  ["userType", true],
  ["name", true],
  ["email", true],
  ["phone", true],
  ["gender", false],
  ["birthday", false],
  ["company", false],
  ["city", false],
  ["country", false],
  ["channel", false],
  ["campDest", false],
  ["campMedia", false],
  ["campName", false],
  ["refHost", false],
  ["refUrl", false],
  ["landingPage", false],
  ["identified", false],
  ["totalTime", false],
  ["totalSession", false],
  ["createdOn", false],
  ["lastSeen", false],
];
